### ISSUE TITLE
print out read info in rw_scen_aggregate()

### ISSUE THREAD

**Issue by rabutler** [BoulderCodeHub/RWDataPlyr#60]
- print out more info on scenarios and files that are being read in
- use a `verbose=TRUE` argument to control this, and can also pass that to `read.rdf()` and `fread()`

**Comment by rabutler-usbr** [comment]
similar/same as #82

**Comment by rabutler-usbr** [comment]
We do not want to use `verbose = TRUE` in `data.table::fread()` as it prints out a bunch of rather unimporant stuff. The `showProgress` option will default to `TRUE` if running in interactive mode, and that will show up if it's expected to take more than 3 seconds. 

Closing this and addressing the rest in #82.
